name: Pulumi Deploy with OIDC

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pulumi-up:
    name: pulumi-up-oidc
    runs-on: ubuntu-latest

    # Add permissions for OIDC
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: ./ppinfra
        run: npm install

      # Configure AWS OIDC authentication
      - name: Configure AWS OIDC Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::650251685614:role/PulumiOIDCDeployRole
          role-session-name: PulumiSession
          aws-region: us-west-2

      # Run Pulumi with OIDC Authentication
      - uses: pulumi/actions@v5
        with:
          command: up
          stack-name: Aishu0110/Dev_lab08/dev
          work-dir: ./ppinfra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
